"""Greenhouse board scraper constants."""

# Default Greenhouse boards to scan when the user doesn't provide specific ones.
# These are well-known startup / remote-friendly companies that use Greenhouse.
# Note: `search_term` filtering happens in-app on the scraper; boards are a
# rotating list of companies a user is most likely to care about.
DEFAULT_BOARDS = [
    "vercel",
    "stripe",
    "airtable",
    "notion",
    "figma",
    "webflow",
    "datadog",
    "zapier",
    "retool",
    "linear",
    "supabase",
    "gitlab",
    "saucelabs",
    "discord",
    "asana",
    "dropbox",
    "canva",
    "pinterest",
    "shopify",
    "gusto",
    "doordash",
    "droneseed",
    "betterhelp",
    "rover",
    "replit",
    "instacart",
    "wayfair",
    "codecademy",
    "render",
    "neondatabase",
    "clerk",
    "workos",
    "sourcegraph",
    "sentry",
    "flight",
    "railway",
    "planetscale",
    "deno",
    "changelog",
    "mercury",
    "check",
    "stytch",
    "transcend",
    "coda",
    "mural",
    "lucid",
    "framer",
    "readwise",
    "mattermost",
    "teleport",
    "grafana",
    "hasura",
    "timescale",
    "bytebase",
    "apollo",
    "grammarly",
    "lattice",
    "substack",
    "ghost",
    "loom",
    "descript",
    "fathom",
    "dbtlabs",
    "astronomer",
    "airbyte",
    "fivetran",
    "segment",
    "algolia",
    "assemblyai",
    "circleci",
    "clickhouse",
    "descope",
    "gradle",
    "hightouch",
    "honeycomb",
    "intercom",
    "iterable",
    "klaviyo",
    "launchdarkly",
    "prisma",
    "stackblitz",
]

# Base URL for the Greenhouse Boards public API
API_BASE = "https://boards-api.greenhouse.io/v1/boards/{board}/jobs"

# Greenhouse date field for sorting / recent detection
LIVE_JOBS_ATTR = "updated_at"